spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/prospera}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Lucas3009!}
spring.flyway.locations=classpath:db/migration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

api.security.token.secret=${JWT_SECRET:my-secret-key}
app.cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:*,http://127.0.0.1:*,https://appprospera.com.br,https://www.appprospera.com.br,https://api.appprospera.com.br,https://*.lovable.app}
